---
# Source: helm for kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cosmetic-websitessssssssss-4dd5788a          # Service name
  labels:
    app: cosmetic-websitessssssssss-4dd5788a
spec:
  type: ClusterIP   # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: cosmetic-websitessssssssss-4dd5788a         # Matches Deployment labels
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: 8080  # Target container port
